services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - 3000:3000
    stdin_open: true
    env_file:
      - .env
    networks:
      - prisma-network

  prisma-studio:
    image: node:18-alpine
    container_name: prisma_studio
    working_dir: /app
    volumes:
      - .:/app
    command: ["npx", "prisma", "studio"]
    ports:
      - "5555:5555"
    env_file:
      - .env

networks:
  prisma-network:
    name: prisma-network